### ISSUE TITLE
> ADD ISSUE DESCRIPTION HERE

### ISSUE THREAD

**Issue by ibbrahiim** [microsoft/vscode-remote-repositories-github#409]
> ADD ISSUE DESCRIPTION HERE
> 
> Version: 1.85.1
> Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
> User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36
> Embedder: vscode.dev
> 
> Extension version: 0.40.0
> 
> ```[tasklist]
> ### Tasks
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/417
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/390
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/419
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/418
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/417
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/417
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/417
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/417
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/417
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/417
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/417
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/383
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/383
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/383
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/416
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/416
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/416
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/383
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/383
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/383
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/383
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/416
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/402
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/383
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/383
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/383
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/416
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/401
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/402
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/402
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/416
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/416
- [x] https://github.com/microsoft/vscode-remote-repositories-github/issues/416
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/402
> ```

_Originally posted by @ibbrahiim in https://github.com/microsoft/vscode-remote-repositories-github/issues/408#issuecomment-1872476574_
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/383
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/416
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/402
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/415
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/383
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/383
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/416
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/390
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/390
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/383
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/417
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/419
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/383
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/418
- [ ] #390
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/247
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/159
- [ ] # 390
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/111
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/377
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/268
```

**Comment by joyceerhl** [comment]
Please provide more details if you're experiencing an issue using vscode.dev, thanks!

**Comment by ibbrahiim** [comment]
/

**Comment by ibbrahiim** [comment]
```coffeescript

```

**Comment by ibbrahiim** [comment]
```c

```

**Comment by ibbrahiim** [comment]
security policy code of conduct

**Comment by ibbrahiim** [comment]
الرجاء إضافة وظيفة تنفيذ طلبات الانسحاب (المراجعة والتعليق والإنشاء) من VSCode. يعد هذا عيبًا مهمًا وأكبر عيب جدًا في Azure DevOps مقارنة بالمنافسين الآخرين مثل GitHub وBitBucket وGitLab - التي تتمتع بتكامل جيد جدًا مع VSCode.
