### ISSUE TITLE
GitHub Repositories: Iteration Plan for August 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-repositories-github#48]
This plan captures our work in **August**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/130368). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### UX
- [x] Rename `Remote Repositories` extension to `GitHub Repositories` @eamodio

### Fundamentals
- [x] :red_circle: Remote repositories selected from history in a remote window show as being on the remote @eamodio @aeschli
- [ ] :red_circle: :runner: Improve first load performance @eamodio
- [ ] :runner: Recommend the GHPRI extension when the users opens a PR [vscode-internalbacklog#2330](https://github.com/microsoft/vscode-internalbacklog/issues/2330) @alexr00 @eamodio
- [ ] :muscle: Explore command line support like `code github.com/org/repo` [vscode-remote-repositories-github#5](https://github.com/microsoft/vscode-remote-repositories-github/issues/5) @eamodio
- [ ] :red_circle: :muscle: Consolidate pickers with the GH core extension and make pickers available for other extensions @eamodio
- [ ] :muscle: Explore how not to get stuck when the user cancels a GitHub sign-in request externally [vscode-remotehub#248](https://github.com/microsoft/vscode-remotehub/issues/248) @eamodio
